### ISSUE TITLE
Failed to activate the text-to-string-for-javascript-converter package

### ISSUE THREAD

**Issue by fincha** [tanadee/text-to-string-for-javascript-converter#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.199.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [text-to-string-for-javascript-converter](https://github.com/tanadee/text-to-string-for-javascript-converter) package, v0.0.7
### Stack Trace

Failed to activate the text-to-string-for-javascript-converter package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.exports.activate (/Users/fribu/.atom/packages/text-to-string-for-javascript-converter/lib/main.js:4:21)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:238:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:219:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:163:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:211:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:435:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:419:29
  at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
  at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:414:19)
  at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:395:46)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:636:21)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:91:23)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:32:7)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
coffeescript-check, v0.0.3
coffeescript-preview, v1.0.0
color-picker, v1.7.0
html-entities, v0.3.1
html-tab, v1.0.1
jshint, v1.3.5
language-lua, v0.9.2
linter, v0.12.1
linter-lua, v0.1.5
linter-luacheck, v0.3.3
text-to-string-for-javascript-converter, v0.0.7

# Dev
No dev packages
```

**Comment by Dashon-Hawkins** [comment]
**I'm having the same exact issue. Can somebody assist me?**

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [text-to-string-for-javascript-converter](https://github.com/tanadee/text-to-string-for-javascript-converter) package 0.0.7


### Stack Trace

Failed to activate the text-to-string-for-javascript-converter package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.exports.activate (/packages/text-to-string-for-javascript-converter/lib/main.js:4:21)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:814:28
```

### Commands

```
     -8:06.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.tinted-tab-bar.compact-tab-bar.panel-shadows.panel-contrast.use-animations.compact-tree-view.blend-tree-view.theme-colorblind-wombat-dark-syntax.theme-atom-material-ui)
     -3:15.8.0 settings-view:open (a.)
```

### Non-Core Packages

```
ajax-request 0.1.0 
angularjs 0.4.0 
atom-beautify 0.29.17 
atom-html-preview 0.1.22 
atom-json-editor 0.4.1 
atom-material-ui 1.3.9 
atom-math 0.0.9 
atom-runner 2.7.1 
atom-ternjs 0.18.2 
atomic-chrome 0.3.0 
atomify 0.2.0 
autoclose-html 0.23.0 
autocomplete-json 5.3.0 
busy 0.7.0 
class-complete 6.2.2 
colorblind-wombat-dark-syntax 0.6.0 
colorful-json 1.1.0 
convert-html-to-js 1.0.1 
css-specificity 0.2.2 
element-finder 0.1.1 
es6-javascript 1.0.0 
eval-javascript 1.2.0 
file-icon-supplement 0.8.3 
file-icons 2.0.17 
Function_Index 0.3.2 
git-plus 7.3.3 
html-head-snippets 0.2.0 
html-id-class-snippets 1.4.1 
html-nested-comments 3.3.1 
html-tab 1.0.2 
html-template-generator 0.3.0 
html-to-css 0.2.2 
html-to-elm 0.2.0 
html-to-javascript 0.2.0 
hyperclick 0.0.40 
incompatible 0.0.0 
increment-selection 0.3.0 
indent-guide-improved 1.4.12 
intentions 1.1.2 
java-classpath-registry 0.4.0 
javascript-object-snippets 0.3.0 
javascript-snippets 1.2.1 
javascript-standard-snippets 0.2.1 
jQuery 1.2.5 
jquery-snippets 11.0.0 
js-func-viewer 1.1.4 
js-patterns-atom-snippets 0.2.1 
json-colorer 1.0.0 
json-path-finder 0.1.9 
jsonpp 0.1.1 
language-fish-shell 1.0.5 
language-javascript-jsx 0.3.7 
language-javascript-semantic 0.2.1 
linter 1.11.23 
linter-json-lint 0.1.1 
linter-spell 0.12.6 
linter-spell-html 0.6.1 
linter-spell-javascript 0.7.1 
pigments 0.39.0 
pretty-json 1.6.1 
Quick-JavaScript 2.2.0 
regex-filter-and-generator 1.4.2 
regex-railroad-diagram 0.16.0 
regex-tester 0.2.0 
save-session 0.15.7 
selector-to-tag 0.4.2 
slack-chat 3.4.2 
sub-atom 1.0.0 
termination 0.5.0 
text-to-string-for-javascript-converter 0.0.7 
turbo-javascript 1.4.0 
```

**Comment by uxen-ab** [comment]
I have the same problem. There is the error report:

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.10.5
**Thrown From**: [text-to-string-for-javascript-converter](https://github.com/tanadee/text-to-string-for-javascript-converter) package 0.0.7


### Stack Trace

Failed to activate the text-to-string-for-javascript-converter package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.exports.activate (/packages/text-to-string-for-javascript-converter/lib/main.js:4:21)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:253:1)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:1
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:1)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:1
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:1)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:642:1)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:519:1
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:1)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:1)
    at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:359:1
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:220:1)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -6:31.8.0 settings-view:open (input.hidden-input)
     -2:38.1.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.1 
intentions 1.1.2 
linter 2.1.4 
linter-ui-default 1.6.0 
linter-xo 0.23.0 
text-to-string-for-javascript-converter 0.0.7 
```

**Comment by Boldbydesign** [comment]
Failed to activate the text-to-string-for-javascript-converter package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.exports.activate (/packages/text-to-string-for-javascript-converter/lib/main.js:4:22)
    at Package.activateNow (C:/ProgramData/Jer/atom/app-1.60.0/resources/app/static/<embedded>:11:3531596)
    at C:/ProgramData/Jer/atom/app-1.60.0/resources/app/static/<embedded>:11:3531008
    at Package.measure (C:/ProgramData/Jer/atom/app-1.60.0/resources/app/static/<embedded>:11:3528586)
    at C:/ProgramData/Jer/atom/app-1.60.0/resources/app/static/<embedded>:11:3530868
    at new Promise (<anonymous>)
    at Package.activate (C:/ProgramData/Jer/atom/app-1.60.0/resources/app/static/<embedded>:11:3530811)
    at PackageManager.activatePackage (C:/ProgramData/Jer/atom/app-1.60.0/resources/app/static/<embedded>:11:386057)
    at C:/ProgramData/Jer/atom/app-1.60.0/resources/app/static/<embedded>:11:915799
    at r (C:/ProgramData/Jer/atom/app-1.60.0/resources/app/static/<embedded>:11:910405)
    at n (C:/ProgramData/Jer/atom/app-1.60.0/resources/app/static/<embedded>:14:1174458)
    at ChildProcess.<anonymous> (C:/ProgramData/Jer/atom/app-1.60.0/resources/app/static/<embedded>:14:1174664)
    at ChildProcess.emit (events.js:223:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.18 
atom-material-ui 2.1.3 
html-to-javascript 0.2.0 
Hydrogen 2.16.3 
javascript-drag-import 0.1.13 
javascript-importer 0.1.0 
puddletown-javascript-node-snippets 1.2.1 
puddletown-javascript-snippets 1.2.1 
Quick-JavaScript 2.2.0 
scroll-through-time 0.3.1 
spell-checker-improved-plugin-javascript 2.0.1 
teletype 0.13.4 
text-to-string-for-javascript-converter 0.0.7 
wakatime 11.0.10 
```
